# used for dev env only
version: '3'
services:
  neo4j:
    image: neo4j:3.4.7
    ports:
      - "30002:7474"
      - "30003:7687"
    environment:
      NEO4J_AUTH: "none"

  rethinkdb:
    image: rethinkdb:2.3.6
    ports:
      - "30004:8080"
      - "30005:28015"

  # web:
  #   image: tmtxt/genealogy:latest
  #   ports:
  #     - "30007:80"
  #   environment:
  #     NEO4J_SERVER: neo4j
  #     NEO4J_PORT: 7687
  #     NEO4J_USER: neo4j
