:host = localhost

# get person by id
GET http://:host:30001/api/person/1

# get root person
GET http://:host:30001/api/root-person

# update person by id
PATCH http://:host:30001/api/person/1
Content-Type: application/json

{
  "name": "HAHAH"
}

# add child
:fatherPersonId = 0
:motherPersonId = 1
POST http://:host:30001/api/persons/add-child/father/:fatherPersonId/mother/:motherPersonId
Content-Type: application/json

{
  "order": 2
}

# add husband
:personId = 1
POST http://:host:30001/api/persons/:personId/add-husband
Content-Type: application/json

{
  "order": 2
}

# add wife
:personId = 0
POST http://:host:30001/api/persons/:personId/add-wife
Content-Type: application/json

{
  "order": 2
}
